export const categories = [
    {
      id: 1,
      name: "Processadores",
      products: [
        {
          id: 1,
          name: "Intel Core i7-12700K",
          price: 2199.99,
          image: "/images/intel-i7.jpg",
          description: "12ª Geração, 12 núcleos, 20 threads, clock base de 3.6GHz.",
        },
        {
          id: 2,
          name: "AMD Ryzen 7 5800X",
          price: 1799.99,
          image: "/images/ryzen-7.jpg",
          description: "8 núcleos, 16 threads, clock base de 3.8GHz.",
        },
        {
          id: 3,
          name: "Intel Core i9-11900K",
          price: 3299.99,
          image: "/images/intel-i9.jpg",
          description: "8 núcleos, 16 threads, até 5.3 GHz de clock turbo.",
        },
        {
          id: 4,
          name: "AMD Ryzen 9 5900X",
          price: 3999.99,
          image: "/images/ryzen-9.jpg",
          description: "12 núcleos, 24 threads, até 4.8GHz de clock.",
        },
        {
          id: 5,
          name: "Intel Core i5-11600K",
          price: 1599.99,
          image: "/images/intel-i5.jpg",
          description: "6 núcleos, 12 threads, 3.9 GHz base.",
        },
        {
          id: 6,
          name: "AMD Ryzen 5 5600X",
          price: 1499.99,
          image: "/images/ryzen-5.jpg",
          description: "6 núcleos, 12 threads, até 4.6GHz.",
        },
        {
          id: 7,
          name: "Intel Core i3-10100F",
          price: 799.99,
          image: "/images/intel-i3.jpg",
          description: "4 núcleos, 8 threads, 3.6 GHz base.",
        },
        {
          id: 8,
          name: "AMD Ryzen 3 3300X",
          price: 899.99,
          image: "/images/ryzen-3.jpg",
          description: "4 núcleos, 8 threads, até 4.3GHz.",
        },
        {
          id: 9,
          name: "Intel Core i7-11700F",
          price: 2499.99,
          image: "/images/intel-i7-11700f.jpg",
          description: "8 núcleos, 16 threads, até 4.9GHz.",
        },
        {
          id: 10,
          name: "AMD Ryzen 7 3700X",
          price: 2299.99,
          image: "/images/ryzen-7-3700x.jpg",
          description: "8 núcleos, 16 threads, até 4.4GHz.",
        },
        {
          id: 11,
          name: "Intel Core i9-10900K",
          price: 3599.99,
          image: "/images/intel-i9-10900k.jpg",
          description: "10 núcleos, 20 threads, até 5.3 GHz de clock turbo.",
        },
        {
          id: 12,
          name: "AMD Ryzen 5 3600X",
          price: 1399.99,
          image: "/images/ryzen-5-3600x.jpg",
          description: "6 núcleos, 12 threads, até 4.4GHz.",
        },
        {
          id: 13,
          name: "Intel Xeon W-2295",
          price: 6499.99,
          image: "/images/intel-xeon.jpg",
          description: "18 núcleos, 36 threads, até 4.6 GHz.",
        },
      ],
    },
    {
      id: 2,
      name: "Placas de Vídeo",
      products: [
        {
          id: 3,
          name: "NVIDIA RTX 4070 Ti",
          price: 5299.99,
          image: "/images/rtx-4070ti.jpg",
          description: "16GB GDDR6X, Ray Tracing, DLSS 3, desempenho incrível.",
        },
        {
          id: 4,
          name: "AMD Radeon RX 6800 XT",
          price: 4599.99,
          image: "/images/radeon-6800xt.jpg",
          description: "16GB GDDR6, performance de alto nível em jogos 4K.",
        },
        {
          id: 5,
          name: "NVIDIA RTX 3080 Ti",
          price: 4499.99,
          image: "/images/rtx-3080ti.jpg",
          description: "12GB GDDR6X, Ray Tracing, ótimo para jogos 4K.",
        },
        {
          id: 6,
          name: "AMD Radeon RX 6900 XT",
          price: 5099.99,
          image: "/images/radeon-6900xt.jpg",
          description: "16GB GDDR6, excelente para jogos e VR.",
        },
        {
          id: 7,
          name: "NVIDIA RTX 3060 Ti",
          price: 3199.99,
          image: "/images/rtx-3060ti.jpg",
          description: "8GB GDDR6, performance ótima para jogos 1080p.",
        },
        {
          id: 8,
          name: "NVIDIA RTX 3070",
          price: 3799.99,
          image: "/images/rtx-3070.jpg",
          description: "8GB GDDR6, boa para jogos 1440p.",
        },
        {
          id: 9,
          name: "AMD Radeon RX 5700 XT",
          price: 2799.99,
          image: "/images/radeon-5700xt.jpg",
          description: "8GB GDDR6, excelente custo-benefício para jogos.",
        },
        {
          id: 10,
          name: "NVIDIA GTX 1660 Ti",
          price: 2199.99,
          image: "/images/gtx-1660ti.jpg",
          description: "6GB GDDR5, ótima para jogos em Full HD.",
        },
        {
          id: 11,
          name: "AMD Radeon RX 580",
          price: 1799.99,
          image: "/images/radeon-rx580.jpg",
          description: "8GB GDDR5, boa para jogos e multitarefa.",
        },
        {
          id: 12,
          name: "NVIDIA RTX 2060 Super",
          price: 2699.99,
          image: "/images/rtx-2060super.jpg",
          description: "8GB GDDR6, desempenho sólido em jogos AAA.",
        },
        {
          id: 13,
          name: "AMD Radeon RX 5600 XT",
          price: 2399.99,
          image: "/images/radeon-5600xt.jpg",
          description: "6GB GDDR6, ótima para jogos em 1080p.",
        },
        {
          id: 14,
          name: "NVIDIA Quadro RTX 4000",
          price: 7999.99,
          image: "/images/quadro-rtx4000.jpg",
          description: "8GB GDDR6, para estações de trabalho e tarefas profissionais.",
        },
      ],
    },
  ];
  